# Generated by Django 3.0 on 2019-12-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('no_telepon', models.CharField(max_length=14)),
                ('bidang', models.CharField(max_length=50)),
                ('jadwal_praktek', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
