# Generated by Django 3.0 on 2019-12-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kandungan', models.CharField(max_length=100)),
                ('khasiat', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('no_telepon', models.CharField(max_length=14)),
                ('alamat', models.CharField(max_length=100)),
                ('keluhan', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('total_harga', models.CharField(max_length=10)),
                ('kumpulan_obat', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
