# Generated by Django 3.0 on 2019-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_obat_pasien_resep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='obat',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='kumpulan_obat',
        ),
        migrations.AddField(
            model_name='resep',
            name='kumpulan_obat',
            field=models.ManyToManyField(to='hospital.Obat'),
        ),
    ]
