# Generated by Django 3.0 on 2019-12-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_blog', models.CharField(max_length=50)),
                ('isi_blog', models.TextField()),
                ('date_blog', models.DateField()),
                ('img_blog', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mentee', models.CharField(max_length=50)),
                ('quote_mentee', models.CharField(max_length=100)),
                ('img_mentee', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mentor', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('quote_mentor', models.CharField(max_length=100)),
                ('img_mentor', models.CharField(max_length=1000)),
            ],
        ),
    ]
