# Generated by Django 3.0 on 2019-12-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livecode',
            name='tgl_pelaksanaan',
            field=models.DateField(null=True),
        ),
    ]
