# Generated by Django 3.0 on 2019-12-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('berat', models.IntegerField(max_length=4)),
                ('umur', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('no_telepon', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Penjaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('no_telepon', models.CharField(max_length=14)),
                ('jadwal_jaga', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kandang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_kandang', models.IntegerField(max_length=3)),
                ('luas_kandang', models.IntegerField(max_length=10)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.Hewan')),
            ],
        ),
    ]
