# Generated by Django 3.0 on 2019-12-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hewan',
            name='berat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='umur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kandang',
            name='isi_kandang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kandang',
            name='luas_kandang',
            field=models.IntegerField(default=0),
        ),
    ]
