# Generated by Django 3.0 on 2019-12-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20191209_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengunjung',
            name='hari_berkunjung',
            field=models.DateField(null=True),
        ),
    ]
